version: '3'
services:
  dekku-mysql:
    container_name: dekku-mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Dekku1234
      - MYSQL_DATABASE=dekkudb
      - MYSQL_USER=sanghu
      - MYSQL_PASSWORD=sanghu
    volumes:
      - mydata:/var/lib/mysql
    restart: always
    networks:
      - dekku-network

  dekku-redis:
    container_name: dekku-redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    restart: always
    networks:
      - dekku-network

  dekku-mongo:
    container_name: dekku-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Dekku1234
    restart: on-failure
    networks:
      - dekku-network

  dekku-backend:
    container_name: dekku-backend
    build: ./spring-dekku
    image: sanghupark/dekku-backend
    depends_on:
      - dekku-mysql
      - dekku-redis
      - dekku-mongo
    ports:
      - '8080:8080'
    volumes:
      - /home/ubuntu/yml/application.yml:/app/config/application.yml
    restart: no
    networks:
      - dekku-network

  dekku-frontend:
    user: root
    container_name: dekku-frontend
    build: ./next-dekku
    image: sanghupark/dekku-frontend
    depends_on:
      - dekku-backend
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
    restart: on-failure
    networks:
      - dekku-network

volumes:
  mydata:
  redisdata:
  mongodata:

networks:
  dekku-network: