version: '3'
services:
  dekku-mysql:
    container_name: dekku-mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Dekku1234
      - MYSQL_USER=dekku-user
      - MYSQL_PASSWORD=Dekku1234
    volumes:
      - mydata:/var/lib/mysql
    restart: always

  dekku-backend:
    container_name: dekku-backend
    build: ./spring-dekku
    image: sanghupark/dekku-backend
    depends_on:
      - dekku-mysql
    restart: on-failure

  dekku-frontend:
    container_name: dekku-frontend
    build: ./next-dekku
    image: sanghupark/dekku-frontend
    depends_on:
      - dekku-backend
    ports:
      - '80:80'
    restart: on-failure

volumes:
  mydata: