spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dekkudb?serverTimezone=Asia/Seoul
    username: root
    password: Dekku1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # oauth2
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: Rsx5vAptmUrSISgUkmDO
            client-secret: 5FDZm8VeAB
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: name, email, age, gender
            client-authentication-method: client_secret_post
          kakao:
            client-name: kakao
            client-id: 49e8b661f0b102fb6d48af8f9d51ae58
            client-secret: QP32lMzg40d7z0PZblH7UQMnUJATkTqU
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_image, profile_nickname, account_email
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaxcvbxzcvasgrgfzv
    accessExpiredTime: 3_600_000 # 1시간
    refreshExpiredTime: 86_400_000 # 1일

# mustache 한글 깨짐
server:
  servlet:
    encoding:
      force-response: true

cloud:
  aws:
    credentials:
      accessKey: AKIAVRUVV4FVT2KWAOET
      secretKey: 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
    s3:
      bucket: dekku-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

# 얘는 logger 를 통해 log 를 남기는거니까 SQL 을 얘로 확인
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace # 쿼리 에서 value 에 ? ? 였던 부분을 뽑아 아래서 값만 따로 로그 출력
